import {StyleSheet} from 'react-native';

const createStyles = ({colors, sizes, font_type, dimensions, commonStyles}) =>
  StyleSheet.create({
    ...commonStyles,
    centeredContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
      padding: sizes.padding,
      width: '100%',
    },
    orderTypeContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      width: '80%',
      marginTop: 30,
    },
    loadingText: {
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.regular,
      color: colors.text,
      marginTop: 15,
      textAlign: 'center',
    },

    box: {
      width: '60%',
      marginVertical: 10,
      borderColor: colors.text,
      borderWidth: 1,
      borderRadius: sizes.borderRadius2,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 50,
    },
    orderTypeButton: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionContainer: {
      width: '90%',
      flexDirection: 'row',
      gap: 10,
      padding: sizes.padding,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionContainer2: {
      width: '90%',
      flexDirection: 'row',
      gap: 10,
      padding: sizes.padding,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 15,
    },
    miniContainer: {
      position: 'absolute',
      top: '90%',
      left: '10%',
    },
    icon: {
      marginVertical: -30,
      width: 200,
      height: 100,
      // marginBottom: 10,
    },
    simpleButton: {
      minWidth: dimensions.width * 0.4,
      padding: 10,
      marginBottom: 0,
      borderRadius: sizes.borderRadius2,
      alignItems: 'flex-end',
      justifyContent: 'flex-end',
    },
    totalAmount: {
      fontSize: 35,
      textTransform: 'uppercase',
      color: colors.fourth,
      fontFamily: font_type.regular,
      marginBottom: 20,
    },
    instruction: {
      fontSize: 28,
      textAlign: 'center',
      marginVertical: 10,
      marginHorizontal: 40,
      // textTransform: 'uppercase',
      color: colors.text,
      fontFamily: font_type.regular,
    },
    paymentMethodsContainer: {
      objectFit: 'cover',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 15,
    },

    paymentMethodIcon: {
      width: dimensions.width * 0.5,
      height: dimensions.height * 0.048,
      paddingHorizontal: 20,
      objectFit: 'contain',
      // marginHorizontal: 10,
    },
    paymentMethodsContainer2: {
      position: 'absolute',
      top: dimensions.height * 0.1,
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 20,
    },
    paymentMethodIcon2: {
      width: dimensions.width * 0.4,
      height: dimensions.height * 0.048,
      paddingHorizontal: 20,
      objectFit: 'contain',
    },
    paymentMethodsContainer3: {
      position: 'absolute',
      top: dimensions.height * 0.1,
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 20,
    },
    paymentMethodIcon3: {
      width: dimensions.width * 0.4,
      height: dimensions.height * 0.08,
      paddingHorizontal: 20,
    },
    totalContainer: {
      width: '100%',
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      padding: sizes.padding,
      backgroundColor: colors.background,
    },
    totalTitle: {
      fontSize: dimensions.width * 0.03,
      fontWeight: 'bold',
      color: colors.text,
    },
    totalBagText: {
      fontSize: dimensions.width * 0.03,
      color: colors.text,
    },
    totalInfo: {
      width: '90%',
      justifyContent: 'center',
    },
    totalActions: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 10,
    },
    totalName: {
      fontSize: dimensions.width * 0.027,
      fontFamily: font_type.regular,
      color: colors.text,
    },
    bagTotal: {
      fontSize: dimensions.width * 0.027,
      color: colors.fourth,
      fontFamily: font_type.regular,
    },
    totalItem: {
      flexDirection: 'row',
      width: '92%',
      marginBottom: 15,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: sizes.borderRadius2,
    },
    totalItem2: {
      flexDirection: 'row',
      width: '92%',
      marginBottom: 15,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.third,
      borderRadius: sizes.borderRadius2,
      backgroundColor: colors.third,
    },
  });

export default createStyles;
