import {StyleSheet} from 'react-native';

export const createStyles = (colors, dimensions, font_type, sizes) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loaderOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 999,
      elevation: 10,
    },
    loaderCorner: {
      position: 'absolute',
      top: 20,
      right: 30,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
      elevation: 12,
    },
    logo: {
      width: 400,
      height: 250,
      resizeMode: 'contain',
      marginBottom: 30,
    },
    mainText: {
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.semibold,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 10,
    },
    mainText2: {
      fontSize: dimensions.width * 0.018,
      fontFamily: font_type.semibold,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 25,
    },
    subText: {
      fontSize: dimensions.width * 0.012,
      fontFamily: font_type.regular,
      color: colors.text,
      textAlign: 'center',
      marginBottom: 10,
    },
    ctaText: {
      fontSize: dimensions.width * 0.013,
      fontFamily: font_type.bold,
      color: colors.primary,
      textAlign: 'center',
      marginVertical: 10,
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 20,
      marginBottom: 20,
    },
    primaryButton: {
      backgroundColor: colors.button,
      paddingVertical: 12,
      width: 180,
      alignItems: 'center',
      borderRadius: sizes.borderRadius,
    },
    secondaryButton: {
      backgroundColor: colors.text,
      paddingVertical: 12,
      width: 180,
      alignItems: 'center',
      borderRadius: sizes.borderRadius,
    },
    primaryButtonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.012,
      paddingHorizontal: 10,
      fontFamily: font_type.regular,
      textTransform: 'uppercase',
    },
    secondaryButtonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.012,
      paddingHorizontal: 10,
      fontFamily: font_type.regular,
      textTransform: 'uppercase',
    },
    centeredContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
      padding: sizes.padding,
      width: '100%',
    },
    instruction: {
      fontSize: 28,
      textAlign: 'center',
      marginVertical: 10,
      color: colors.text,
      fontFamily: font_type.regular,
    },
    cta: {
      fontSize: 32,
      textAlign: 'center',
      marginVertical: 30,
      color: colors.fourth,
      fontFamily: font_type.regular,
    },
    paymentMethodsContainer: {
      position: 'absolute',
      top: dimensions.height * 0.1,
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 20,
    },
    paymentMethodIcon: {
      width: dimensions.width * 0.4,
      height: dimensions.height * 0.048,
      paddingHorizontal: 20,
      objectFit: 'contain',
    },
    loadingText: {
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.regular,
      color: colors.text,
      marginTop: 15,
      textAlign: 'center',
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.white,
      padding: sizes.padding,
      width: '100%',
    },
    errorText: {
      fontSize: dimensions.width * 0.016,
      fontFamily: font_type.regular,
      color: colors.error || colors.text,
      textAlign: 'center',
      marginBottom: 30,
      marginTop: 20,
    },
    callWaiterButton: {
      backgroundColor: colors.error || colors.secondary,
      paddingVertical: 15,
      paddingHorizontal: 30,
      borderRadius: sizes.borderRadius,
      alignSelf: 'center',
    },
    buttonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.012,
      fontFamily: font_type.semibold,
      textAlign: 'center',
    },
  });
