import {StyleSheet} from 'react-native';

export const createStyles = (colors, dimensions, font_type, sizes) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 30,
    },
    logo: {
      width: dimensions.width * 0.4,
      height: dimensions.height * 0.3,
      resizeMode: 'contain',
      marginBottom: 0,
    },
    instruction: {
      fontSize: dimensions.width * 0.02,
      textAlign: 'center',
      color: colors.text,
      fontFamily: font_type.lite,
      marginBottom: 20,
    },
    question: {
      fontSize: dimensions.width * 0.016,
      fontFamily: font_type.semibold,
      color: colors.text,
      marginTop: 20,
      marginBottom: 20,
    },
    cta: {
      fontSize: dimensions.width * 0.05,
      color: colors.fourth,
      fontFamily: font_type.regular,
      marginVertical: 10,
      marginTop: 25,
    },
    confirmedText: {
      fontSize: dimensions.width * 0.022,
      fontFamily: font_type.semibold,
      color: colors.text,
      marginBottom: 40,
      marginTop: 30,
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 20,
    },
    primaryButton: {
      backgroundColor: colors.button,
      paddingVertical: 12,
      width: 180,
      alignItems: 'center',
      borderRadius: sizes.borderRadius,
    },
    secondaryButton: {
      backgroundColor: colors.text,
      paddingVertical: 12,
      width: 180,
      alignItems: 'center',
      borderRadius: sizes.borderRadius,
    },
    primaryButtonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.012,
      paddingHorizontal: 10,
      fontFamily: font_type.regular,
      textTransform: 'uppercase',
    },
    secondaryButtonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.012,
      paddingHorizontal: 10,
      fontFamily: font_type.regular,
      textTransform: 'uppercase',
    },
    checkAnimation: {
      width: 300,
      height: 300,
      marginBottom: 0,
      marginTop: 0,
    },
    scrollView: {
      maxHeight: dimensions.height * 0.2,
      width: '32%',
      marginVertical: 15,
    },
    scrollViewContent: {
      alignItems: 'center',
    },
    orderSummaryText: {
      fontSize: dimensions.width * 0.015,
      textAlign: 'center',
      color: colors.text,
      fontFamily: font_type.regular,
      marginBottom: 5,
    },
    progressButton: {
      width: 300,
      height: 50,
      borderRadius: sizes.borderRadius,
      overflow: 'hidden',
      justifyContent: 'center',
      marginVertical: 15,
    },
    progressBar: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      backgroundColor: colors.button,
    },
    progressButtonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.semibold,
      textAlign: 'center',
      zIndex: 1,
    },
    backLinkContainer: {
      marginTop: 15,
      paddingVertical: 12,
      paddingHorizontal: 30,
      backgroundColor: '#E5E5E5',
      borderRadius: 25,
      alignSelf: 'center',
    },
    backLinkText: {
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.semibold,
      color: colors.text,
      textAlign: 'center',
    },
  });
