import {StyleSheet} from 'react-native';

export const createStyles = (colors, dimensions, font_type, sizes) =>
  StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.white,
      padding: 10,
    },
    backButton: {
      zIndex: 20,
      position: 'absolute',
      top: 0,
      left: 0,
      padding: 10,
    },
    titleContainer: {
      width: '100%',
      fontWeight: 'bold',
      fontSize: dimensions.width * 0.03,
      fontFamily: 'System',
      textAlign: 'center',
      color: colors.secondary,
    },
    logo: {
      width: dimensions.width * 1.8,
      height: dimensions.height * 0.2,
      resizeMode: 'contain',
      marginBottom: 0,
      position: 'absolute',
      top: 20,
      right: 0,
      opacity: 0.5,
    },
    inputContainer: {
      width: dimensions.width * 0.55,
      marginBottom: 10,
      paddingHorizontal: 10,
      borderRadius: 20,
    },
    input: {
      width: '100%',
      height: dimensions.height * 0.075,
      borderColor: colors.text,
      borderWidth: 1,
      paddingHorizontal: 15,
      backgroundColor: colors.white,
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.lite,
    },
    inputDisabled: {
      width: '100%',
      height: dimensions.height * 0.075,
      borderColor: colors.disabled || '#CCCCCC',
      borderWidth: 1,
      paddingHorizontal: 15,
      backgroundColor: colors.background || '#F5F5F5',
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.lite,
      color: colors.disabled || '#CCCCCC',
    },
    inputText: {
      color: colors.text,
      fontSize: dimensions.width * 0.018,
      marginBottom: 5,
      fontFamily: font_type.semibold,
    },
    titleText: {
      color: colors.text,
      fontSize: dimensions.width * 0.018,
      marginBottom: 5,
      fontFamily: font_type.semibold,
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '40%',
      marginTop: dimensions.width * 0.01,
    },
    button: {
      backgroundColor: colors.button,
      padding: 10,
      borderRadius: sizes.borderRadius,
      width: '45%',
      alignItems: 'center',
      marginTop: 15,
    },
    buttonDisabled: {
      backgroundColor: colors.disabled || '#CCCCCC',
      opacity: 0.7,
    },
    loaderContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    infoContainer: {
      backgroundColor: colors.background || '#F5F5F5',
      padding: 15,
      marginTop: 10,
      //   marginHorizontal: 40,
      //   borderLeftWidth: 4,
      //   borderLeftColor: colors.button,
    },
    infoText: {
      color: colors.text || '#333',
      fontSize: dimensions.width * 0.014,
      fontFamily: font_type.lite,
      textAlign: 'center',
      fontStyle: 'italic',
    },
    backButtonStyle: {
      backgroundColor: colors.text || '#6c757d',
      padding: 10,
      borderRadius: sizes.borderRadius,
      width: '45%',
      alignItems: 'center',
      marginTop: 15,
    },
    buttonText: {
      color: colors.white,
      fontSize: dimensions.width * 0.018,
      fontFamily: font_type.semibold,
    },
    pickerStyle: {
      fontSize: dimensions.width * 0.014,
      paddingVertical: 14,
      paddingHorizontal: 15,
      borderWidth: 1,
      borderColor: colors.button,
      color: '#000',
      backgroundColor: colors.white,
      fontFamily: font_type.lite,
      borderRadius: sizes.borderRadius,
    },
    pickerStyleDisabled: {
      fontSize: dimensions.width * 0.014,
      paddingVertical: 14,
      paddingHorizontal: 15,
      borderWidth: 1,
      borderColor: colors.disabled || '#CCCCCC',
      borderRadius: sizes.borderRadius2,
      color: colors.disabled || '#CCCCCC',
      backgroundColor: colors.background || '#F5F5F5',
      fontFamily: font_type.lite,
    },
    pickerContainer: {
      height: dimensions.height * 0.075,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.text,
      color: colors.text,
    },
    mainContentContainer: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 20,
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15,
      paddingHorizontal: 10,
      width: '100%',
      justifyContent: 'center',
    },
    toggleButton: {
      backgroundColor: colors.white,
      borderWidth: 2,
      borderColor: colors.button,
      borderRadius: sizes.borderRadius,
      paddingVertical: 10,
      paddingHorizontal: 0,
      minWidth: dimensions.width * 0.3,
      alignItems: 'center',
      justifyContent: 'center',
    },
    toggleButtonActive: {
      backgroundColor: colors.button,
      borderColor: colors.button,
    },
    toggleButtonDisabled: {
      borderColor: colors.disabled || '#CCCCCC',
      backgroundColor: colors.background || '#F5F5F5',
      opacity: 0.5,
    },
    toggleButtonText: {
      color: colors.text,
      fontSize: dimensions.width * 0.016,
      fontFamily: font_type.semibold,
      textAlign: 'center',
    },
    toggleButtonTextActive: {
      color: colors.white,
    },
    checkboxText: {
      color: colors.text,
      fontSize: dimensions.width * 0.016,
      fontFamily: font_type.lite,
      marginLeft: 10,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderWidth: 2,
      borderColor: colors.button,
      borderRadius: 3,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkboxChecked: {
      backgroundColor: colors.button,
    },
    checkboxDisabled: {
      borderColor: colors.disabled || '#CCCCCC',
      backgroundColor: colors.background || '#F5F5F5',
      opacity: 0.5,
    },
    checkMark: {
      color: colors.white,
      fontSize: 12,
      fontWeight: 'bold',
    },
    keyboardAvoidingView: {
      flex: 1,
      backgroundColor: '#fff',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.white,
    },
    loadingContent: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 20,
    },
    loadingText: {
      color: colors.text,
      fontSize: dimensions.width * 0.018,
      marginTop: 15,
      fontFamily: font_type.lite,
      textAlign: 'center',
    },
  });
